name: project_yellow_cake
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  dotted_border: ^2.1.0
  flame: ^1.24.0
  flame_texturepacker: ^4.1.5
  flutter:
    sdk: flutter

  logging: ^1.3.0
  path: ^1.9.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/textures/
  shaders:
    - shaders/explosion_distort.frag
  fonts:
    - family: PixelPlay
      fonts:
        - asset: fonts/pixelplay.ttf
    - family: Resource
      fonts:
        - asset: fonts/resource.ttf
