name: nukleon
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  auto_injector: ^2.1.0
  collection: ^1.19.0
  dotted_border: ^2.1.0
  equatable: ^2.0.7
  flame: ^1.24.0
  flame_texturepacker: ^4.1.5
  flutter:
    sdk: flutter
  logging: ^1.3.0
  path: ^1.9.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: false
  assets:
    - assets/
    - assets/backdrops/
    - assets/images/textures/
  shaders:
    - shaders/explosion_distort.frag
    - shaders/ve_pixelate.frag
    - shaders/ve_posterize.frag
    - shaders/ve_sepia.frag
  fonts:
    - family: PixelPlay
      fonts:
        - asset: fonts/pixelplay.ttf
    - family: Resource
      fonts:
        - asset: fonts/resource.ttf
    - family: Nokia Cellphone FC
      fonts:
        - asset: fonts/nokiafc22.ttf
    - family: "Motorola Screentype"
      fonts:
        - asset: fonts/MotorolaScreentype.ttf