name: project_yellow_cake
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flame: ^1.24.0
  flame_texturepacker: ^4.1.5
  flutter:
    sdk: flutter

  logging: ^1.3.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/textures/
  shaders:
    - shaders/explosion_distort.frag